-- CreateTable
CREATE TABLE "BoxSetComponent" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "boxSetId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "required" BOOLEAN NOT NULL DEFAULT true,
    "count" INTEGER,
    "position" INTEGER NOT NULL DEFAULT 0,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "BoxSetComponent_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "BoxSetComponent_boxSetId_idx" ON "BoxSetComponent"("boxSetId");

-- CreateIndex
CREATE INDEX "BoxSetComponent_type_idx" ON "BoxSetComponent"("type");

-- AddForeignKey
ALTER TABLE "BoxSetComponent" ADD CONSTRAINT "BoxSetComponent_boxSetId_fkey" FOREIGN KEY ("boxSetId") REFERENCES "BoxSet"("id") ON DELETE CASCADE ON UPDATE CASCADE;
