import { Request, Response } from 'express';
import { PrismaClient, EntryStatus } from '@prisma/client';

const prisma = new PrismaClient();

// Component type definition
interface Component {
  type: string;
  name: string;
  required: boolean;
  count?: number;
}

// Helper function to auto-generate components from box set flags
function generateComponentsFromFlags(boxSet: any): Component[] {
  const components: Component[] = [];

  // Slipcover
  if (boxSet.hasSlipcover) {
    components.push({
      type: 'slipcover',
      name: 'Slipcover',
      required: true,
    });
  }

  // Booklet
  if (boxSet.hasBooklet) {
    components.push({
      type: 'booklet',
      name: 'Booklet',
      required: true,
    });
  }

  // Bonus discs
  if (boxSet.hasBonusDisc) {
    const count = boxSet.bonusDiscCount || 1;
    for (let i = 1; i <= count; i++) {
      components.push({
        type: 'disc',
        name: count > 1 ? `Bonus Disc ${i}` : 'Bonus Disc',
        required: true,
      });
    }
  }

  // Digital copy
  if (boxSet.hasDigitalCopy) {
    components.push({
      type: 'digital_code',
      name: 'Digital Copy Code',
      required: true,
    });
  }

  // 3D discs (if applicable)
  if (boxSet.has3d) {
    components.push({
      type: 'disc',
      name: '3D Disc',
      required: true,
    });
  }

  // Package type based components
  if (boxSet.packageType) {
    const pkgType = boxSet.packageType.toLowerCase();
    if (pkgType.includes('slipcase')) {
      components.push({
        type: 'outer_case',
        name: 'Slipcase',
        required: true,
      });
    } else if (pkgType.includes('digipak')) {
      components.push({
        type: 'case',
        name: 'Digipak',
        required: true,
      });
    } else if (pkgType.includes('steelbook')) {
      components.push({
        type: 'case',
        name: 'Steelbook',
        required: true,
      });
    }
  }

  // Edition-based components
  if (boxSet.edition) {
    const editionLower = boxSet.edition.toLowerCase();
    if (editionLower.includes('criterion')) {
      components.push({
        type: 'booklet',
        name: 'Criterion Booklet',
        required: true,
      });
    }
    if (editionLower.includes('poster')) {
      components.push({
        type: 'poster',
        name: 'Poster',
        required: true,
      });
    }
    if (editionLower.includes('art cards') || editionLower.includes('postcards')) {
      components.push({
        type: 'art_cards',
        name: 'Art Cards',
        required: true,
      });
    }
  }

  return components;
}

// GET /api/box-sets - List all box sets with search and pagination
export async function getAllBoxSets(req: Request, res: Response): Promise<void> {
  try {
    const { search, format, sortBy = 'createdAt', sortOrder = 'desc', limit = 50, offset = 0 } = req.query;

    const where: any = {};

    // Search by name or notes
    if (search) {
      where.OR = [
        { name: { contains: search as string, mode: 'insensitive' } },
        { notes: { contains: search as string, mode: 'insensitive' } },
      ];
    }

    // Filter by format
    if (format) {
      where.format = format;
    }

    const [boxSets, total] = await Promise.all([
      prisma.boxSet.findMany({
        where,
        include: {
          items: {
            include: {
              movie: {
                select: {
                  id: true,
                  title: true,
                  year: true,
                  posterUrl: true,
                },
              },
            },
            orderBy: { position: 'asc' },
          },
          releases: {
            select: { id: true },
          },
        },
        orderBy: { [sortBy as string]: sortOrder },
        take: Number(limit),
        skip: Number(offset),
      }),
      prisma.boxSet.count({ where }),
    ]);

    // Format response
    const formattedBoxSets = boxSets.map(boxSet => {
      const autoGeneratedComponents = generateComponentsFromFlags(boxSet);

      return {
        id: `boxset-${boxSet.id}`,
        name: boxSet.name,
        format: boxSet.format,
        region: boxSet.region,
        edition: boxSet.edition,
        packageType: boxSet.packageType,
        coverImageUrl: boxSet.coverImageUrl,
        spineImageUrl: boxSet.spineImageUrl,
        movieCount: boxSet.items.length,
        releaseCount: boxSet.releases?.length || 0,
        components: autoGeneratedComponents,
        createdAt: boxSet.createdAt,
        movies: boxSet.items.map(item => ({
          id: item.movie?.id ? `movie-${item.movie.id}` : null,
          title: item.movie?.title,
          year: item.movie?.year,
          posterUrl: item.movie?.posterUrl,
          position: item.position,
          discNumber: item.discNumber,
          discLabel: item.discLabel,
          isPresent: item.isPresent,
        })),
      };
    });

    res.json({
      boxSets: formattedBoxSets,
      total,
      limit: Number(limit),
      offset: Number(offset),
    });
  } catch (err) {
    console.error('Failed to get box sets:', err);
    res.status(500).json({ error: 'Failed to get box sets' });
  }
}

// GET /api/box-sets/:id - Get a single box set with all details
export async function getBoxSet(req: Request, res: Response): Promise<void> {
  try {
    const { id } = req.params;
    const rawId = id.replace(/^boxset-/, '');

    const boxSet = await prisma.boxSet.findUnique({
      where: { id: rawId },
      include: {
        items: {
          include: {
            movie: {
              select: {
                id: true,
                title: true,
                year: true,
                posterUrl: true,
                backdropUrl: true,
                tagline: true,
                plot: true,
                rating: true,
                runtime: true,
              },
            },
            physicalCopy: {
              select: {
                id: true,
              },
            },
          },
          orderBy: { position: 'asc' },
        },
        releases: {
          select: { id: true, movieId: true },
        },
      },
    });

    if (!boxSet) {
      res.status(404).json({ error: 'Box set not found' });
      return;
    }

    // Auto-generate components from flags
    const autoGeneratedComponents = generateComponentsFromFlags(boxSet);

    // Format response
    const formatted = {
      id: `boxset-${boxSet.id}`,
      name: boxSet.name,
      format: boxSet.format,
      region: boxSet.region,
      edition: boxSet.edition,
      packageType: boxSet.packageType,
      notes: boxSet.notes,
      coverImageUrl: boxSet.coverImageUrl,
      spineImageUrl: boxSet.spineImageUrl,
      hasSlipcover: boxSet.hasSlipcover,
      hasBooklet: boxSet.hasBooklet,
      hasBonusDisc: boxSet.hasBonusDisc,
      bonusDiscCount: boxSet.bonusDiscCount,
      hasDigitalCopy: boxSet.hasDigitalCopy,
      has3d: boxSet.has3d,
      components: autoGeneratedComponents,
      createdAt: boxSet.createdAt,
      updatedAt: boxSet.updatedAt,
      movies: boxSet.items.map(item => ({
        id: item.movie?.id ? `movie-${item.movie.id}` : null,
        boxSetItemId: item.id,
        title: item.movie?.title,
        year: item.movie?.year,
        posterUrl: item.movie?.posterUrl,
        backdropUrl: item.movie?.backdropUrl,
        plot: item.movie?.plot,
        rating: item.movie?.rating,
        runtime: item.movie?.runtime,
        position: item.position,
        discNumber: item.discNumber,
        discLabel: item.discLabel,
        isPresent: item.isPresent,
        physicalCopyId: item.physicalCopy?.id ? `rel-${item.physicalCopy.id}` : null,
      })),
      releases: boxSet.releases?.map(r => ({
        id: `rel-${r.id}`,
        movieId: r.movieId ? `movie-${r.movieId}` : null,
      })) || [],
    };

    res.json({ boxSet: formatted });
  } catch (err) {
    console.error('Failed to get box set:', err);
    res.status(500).json({ error: 'Failed to get box set' });
  }
}

// POST /api/box-sets - Create a new box set (simplified from CineShelf version)
export async function createBoxSet(req: Request, res: Response): Promise<void> {
  try {
    const {
      name,
      format,
      region,
      edition,
      packageType,
      notes,
      coverImageUrl,
      spineImageUrl,
      hasSlipcover,
      hasBooklet,
      hasBonusDisc,
      bonusDiscCount,
      hasDigitalCopy,
      has3d,
    } = req.body;

    if (!name) {
      res.status(400).json({ error: 'Name is required' });
      return;
    }

    const boxSet = await prisma.boxSet.create({
      data: {
        name,
        format: format || null,
        region: region || null,
        edition: edition || null,
        packageType: packageType || null,
        notes: notes || null,
        coverImageUrl: coverImageUrl || null,
        spineImageUrl: spineImageUrl || null,
        hasSlipcover: hasSlipcover ?? false,
        hasBooklet: hasBooklet ?? false,
        hasBonusDisc: hasBonusDisc ?? false,
        bonusDiscCount: bonusDiscCount || null,
        hasDigitalCopy: hasDigitalCopy ?? false,
        has3d: has3d ?? false,
        status: EntryStatus.VERIFIED,
      },
    });

    res.status(201).json({
      boxSet: {
        id: `boxset-${boxSet.id}`,
        name: boxSet.name,
        format: boxSet.format,
      },
    });
  } catch (err) {
    console.error('Failed to create box set:', err);
    res.status(500).json({ error: 'Failed to create box set' });
  }
}

// PUT /api/box-sets/:id - Update box set metadata
export async function updateBoxSet(req: Request, res: Response): Promise<void> {
  try {
    const { id } = req.params;
    const rawId = id.replace(/^boxset-/, '');
    const {
      name,
      format,
      region,
      edition,
      packageType,
      notes,
      coverImageUrl,
      spineImageUrl,
      hasSlipcover,
      hasBooklet,
      hasBonusDisc,
      bonusDiscCount,
      hasDigitalCopy,
      has3d,
    } = req.body;

    const boxSet = await prisma.boxSet.update({
      where: { id: rawId },
      data: {
        ...(name !== undefined && { name }),
        ...(format !== undefined && { format }),
        ...(region !== undefined && { region }),
        ...(edition !== undefined && { edition }),
        ...(packageType !== undefined && { packageType }),
        ...(notes !== undefined && { notes }),
        ...(coverImageUrl !== undefined && { coverImageUrl }),
        ...(spineImageUrl !== undefined && { spineImageUrl }),
        ...(hasSlipcover !== undefined && { hasSlipcover }),
        ...(hasBooklet !== undefined && { hasBooklet }),
        ...(hasBonusDisc !== undefined && { hasBonusDisc }),
        ...(bonusDiscCount !== undefined && { bonusDiscCount }),
        ...(hasDigitalCopy !== undefined && { hasDigitalCopy }),
        ...(has3d !== undefined && { has3d }),
      },
    });

    res.json({
      boxSet: {
        id: `boxset-${boxSet.id}`,
        name: boxSet.name,
      },
    });
  } catch (err) {
    console.error('Failed to update box set:', err);
    res.status(500).json({ error: 'Failed to update box set' });
  }
}

// DELETE /api/box-sets/:id - Delete box set
export async function deleteBoxSet(req: Request, res: Response): Promise<void> {
  try {
    const { id } = req.params;
    const rawId = id.replace(/^boxset-/, '');

    await prisma.boxSet.delete({ where: { id: rawId } });

    res.json({ success: true, message: 'Box set deleted' });
  } catch (err) {
    console.error('Failed to delete box set:', err);
    res.status(500).json({ error: 'Failed to delete box set' });
  }
}

// POST /api/box-sets/:id/movies - Add a movie to box set
export async function addMovieToBoxSet(req: Request, res: Response): Promise<void> {
  try {
    const { id } = req.params;
    const rawId = id.replace(/^boxset-/, '');
    const { movieId, position, discNumber, discLabel, isPresent = true } = req.body;

    if (!movieId) {
      res.status(400).json({ error: 'movieId is required' });
      return;
    }

    const rawMovieId = movieId.replace(/^movie-/, '');

    const item = await prisma.boxSetItem.create({
      data: {
        boxSetId: rawId,
        movieId: rawMovieId,
        position: position || 0,
        discNumber: discNumber || null,
        discLabel: discLabel || null,
        isPresent: isPresent ?? true,
      },
    });

    res.status(201).json({
      item: {
        id: item.id,
        movieId: `movie-${item.movieId}`,
        position: item.position,
      },
    });
  } catch (err) {
    console.error('Failed to add movie to box set:', err);
    res.status(500).json({ error: 'Failed to add movie to box set' });
  }
}

// DELETE /api/box-sets/:id/movies/:movieId - Remove movie from box set
export async function removeMovieFromBoxSet(req: Request, res: Response): Promise<void> {
  try {
    const { id, movieId } = req.params;
    const rawId = id.replace(/^boxset-/, '');
    const rawMovieId = movieId.replace(/^movie-/, '');

    await prisma.boxSetItem.deleteMany({
      where: {
        boxSetId: rawId,
        movieId: rawMovieId,
      },
    });

    res.json({ success: true, message: 'Movie removed from box set' });
  } catch (err) {
    console.error('Failed to remove movie from box set:', err);
    res.status(500).json({ error: 'Failed to remove movie from box set' });
  }
}

// PUT /api/box-sets/:id/movies/:movieId - Update movie position/disc info
export async function updateBoxSetMovie(req: Request, res: Response): Promise<void> {
  try {
    const { id, movieId } = req.params;
    const rawId = id.replace(/^boxset-/, '');
    const rawMovieId = movieId.replace(/^movie-/, '');
    const { position, discNumber, discLabel, isPresent } = req.body;

    const item = await prisma.boxSetItem.updateMany({
      where: {
        boxSetId: rawId,
        movieId: rawMovieId,
      },
      data: {
        ...(position !== undefined && { position }),
        ...(discNumber !== undefined && { discNumber }),
        ...(discLabel !== undefined && { discLabel }),
        ...(isPresent !== undefined && { isPresent }),
      },
    });

    res.json({ success: true, updated: item.count });
  } catch (err) {
    console.error('Failed to update box set movie:', err);
    res.status(500).json({ error: 'Failed to update box set movie' });
  }
}

// GET /api/box-sets/:id/components - Get all components (auto-generated + manual)
export async function getBoxSetComponents(req: Request, res: Response): Promise<void> {
  try {
    const { id } = req.params;
    const rawId = id.replace(/^boxset-/, '');

    const boxSet = await prisma.boxSet.findUnique({
      where: { id: rawId },
      include: {
        components: {
          orderBy: { position: 'asc' },
        },
      },
    });

    if (!boxSet) {
      res.status(404).json({ error: 'Box set not found' });
      return;
    }

    // Get auto-generated components
    const autoGenerated = generateComponentsFromFlags(boxSet);

    // Get manual components from database
    const manualComponents = boxSet.components.map(c => ({
      id: c.id,
      type: c.type,
      name: c.name,
      required: c.required,
      count: c.count,
      position: c.position,
      isAutoGenerated: c.isAutoGenerated,
    }));

    res.json({
      components: {
        autoGenerated,
        manual: manualComponents,
        all: [...autoGenerated, ...manualComponents],
      },
    });
  } catch (err) {
    console.error('Failed to get components:', err);
    res.status(500).json({ error: 'Failed to get components' });
  }
}

// POST /api/box-sets/:id/components - Add a manual component
export async function addBoxSetComponent(req: Request, res: Response): Promise<void> {
  try {
    const { id } = req.params;
    const rawId = id.replace(/^boxset-/, '');
    const { type, name, required = true, count, position = 0 } = req.body;

    if (!type || !name) {
      res.status(400).json({ error: 'Type and name are required' });
      return;
    }

    const component = await prisma.boxSetComponent.create({
      data: {
        boxSetId: rawId,
        type,
        name,
        required,
        count: count || null,
        position,
        isAutoGenerated: false,
      },
    });

    res.status(201).json({
      component: {
        id: component.id,
        type: component.type,
        name: component.name,
        required: component.required,
        count: component.count,
        position: component.position,
      },
    });
  } catch (err) {
    console.error('Failed to add component:', err);
    res.status(500).json({ error: 'Failed to add component' });
  }
}

// PUT /api/box-sets/:id/components/:componentId - Update a component
export async function updateBoxSetComponent(req: Request, res: Response): Promise<void> {
  try {
    const { id, componentId } = req.params;
    const rawId = id.replace(/^boxset-/, '');
    const { type, name, required, count, position } = req.body;

    // Verify the component belongs to this box set
    const existing = await prisma.boxSetComponent.findFirst({
      where: {
        id: componentId,
        boxSetId: rawId,
      },
    });

    if (!existing) {
      res.status(404).json({ error: 'Component not found' });
      return;
    }

    const component = await prisma.boxSetComponent.update({
      where: { id: componentId },
      data: {
        ...(type !== undefined && { type }),
        ...(name !== undefined && { name }),
        ...(required !== undefined && { required }),
        ...(count !== undefined && { count }),
        ...(position !== undefined && { position }),
      },
    });

    res.json({
      component: {
        id: component.id,
        type: component.type,
        name: component.name,
        required: component.required,
        count: component.count,
        position: component.position,
      },
    });
  } catch (err) {
    console.error('Failed to update component:', err);
    res.status(500).json({ error: 'Failed to update component' });
  }
}

// DELETE /api/box-sets/:id/components/:componentId - Delete a component
export async function deleteBoxSetComponent(req: Request, res: Response): Promise<void> {
  try {
    const { id, componentId } = req.params;
    const rawId = id.replace(/^boxset-/, '');

    // Verify the component belongs to this box set
    const existing = await prisma.boxSetComponent.findFirst({
      where: {
        id: componentId,
        boxSetId: rawId,
      },
    });

    if (!existing) {
      res.status(404).json({ error: 'Component not found' });
      return;
    }

    await prisma.boxSetComponent.delete({
      where: { id: componentId },
    });

    res.json({ success: true, message: 'Component deleted' });
  } catch (err) {
    console.error('Failed to delete component:', err);
    res.status(500).json({ error: 'Failed to delete component' });
  }
}

// POST /api/box-sets/:id/components/sync - Persist auto-generated components to database
export async function syncBoxSetComponents(req: Request, res: Response): Promise<void> {
  try {
    const { id } = req.params;
    const rawId = id.replace(/^boxset-/, '');

    const boxSet = await prisma.boxSet.findUnique({
      where: { id: rawId },
    });

    if (!boxSet) {
      res.status(404).json({ error: 'Box set not found' });
      return;
    }

    // Generate components from flags
    const autoGenerated = generateComponentsFromFlags(boxSet);

    // Delete existing auto-generated components
    await prisma.boxSetComponent.deleteMany({
      where: {
        boxSetId: rawId,
        isAutoGenerated: true,
      },
    });

    // Insert new auto-generated components
    const components = await prisma.boxSetComponent.createMany({
      data: autoGenerated.map((c, index) => ({
        boxSetId: rawId,
        type: c.type,
        name: c.name,
        required: c.required,
        count: c.count,
        position: index,
        isAutoGenerated: true,
      })),
    });

    res.json({
      success: true,
      synced: components.count,
      message: `Synced ${components.count} auto-generated components`,
    });
  } catch (err) {
    console.error('Failed to sync components:', err);
    res.status(500).json({ error: 'Failed to sync components' });
  }
}
